Feature/pricing page
inlivedev/inlive-website pull request #99
Opened 2022-04-22 06:50 UTC by ingrid011

**Description**
This is a new feature of pricing page according to issue [#97](https://github.com/asumsi/inlive-website/issues/97) . 

**Implementation**
The implementations are as per below :

- On landing page : delete pricing paragraph
Creating pricing page : when we click on Pricing tab on menu bar then it will direct to this new pricing page : 
- Pricing cards
- FAQ section
- Responsive desktop - mobile : Pricing cards (if on mobile view, it will be scrolled horizontally)
- Responsive desktop - mobile : FAQ
- Testing end to end flow to pricing page (I'm using codeceptJS with Playwright. I've already written it in README.md file too)

However, for the FAQ sections are still using dummy data from https://streamshark.io/live-streaming/pricing/ according to mas @pakzam information on issue [#97](https://github.com/asumsi/inlive-website/issues/97).
Kindly advise for the FAQ content if there is any changes later on mas @bernardsuryawan .

Link preview : https://e518f868.inlive-website.pages.dev/pricing/

2022-04-25 03:38 UTC, faiq-naufal reviewed
@ingrid011  Tadi sempat ngereview beberapa untuk PR ini terutama untuk implementasi codeceptjs nya kelihatannya bisa lebih diimprove lagi terutama dalam mengatur struktur filenya. Biasanya untuk masing-masing file yang berkaitan dengan testing itu dimasukkan ke folder khusus test. Foldernya bisa dinamakan `__tests__ ` atau `tests` atau mungkin karena ini lebih specific end2end pakai codeceptjs, foldernya bisa juga dinamakan `codeceptjs`. Di dalam folder tersebut semua config dan file yang berkaitan dengan codeceptjs ditaruh disitu. Untuk masing-masing test file nya terserah mau diatur strukturnya seperti gimana tapi coba dipikirkan lagi terkait structure projectnya untuk testing agar bisa lebih scalable mau seperti apa. Mungkin bisa jadi referensi structure file yang ada di [blog ini](https://medium.com/successivetech/codeceptjs-skeleton-9ba86d3b45ec) 

Selain itu, ada beberapa tambahan comment juga ya. Bisa tolong dicek juga.

2022-06-08 12:05 UTC, faiq-naufal requested changes
@ingrid011 sorry, ada update sedikit, tolong dicek commentnya ya

2022-06-08 12:50 UTC, faiq-naufal approved these changes

2022-06-08 12:58 UTC, merged

2025-08-19 10:22 UTC, danowar2 approved these changes